version: '3.9'

services:
  backend:
    build: ./server
    container_name: server
    ports:
      - '3000:3000'
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:3000/api # or your actual API URL
    container_name: client
    ports:
      - '5173:80'
    restart: always
